### ISSUE TITLE
PyPi package requires Python ==3.10.5

### ISSUE THREAD

**Issue by tuky** [Riminder/hrflow-connectors#128]
Hi and first of all thx for your project. The latest PyPi package of this project has the way too strict requirement `Python ==3.10.5`. Probably you intended `>=`?

Best

**Comment by the-forest-tree** [comment]
Hi @tuky  

Thank you for reporting. I was solved by [PR](https://github.com/Riminder/hrflow-connectors/pull/136) following your issue a while a ago but we missed replying to your actual issue. 

Since then python versions from 3.7 are supported and both core and integration tests are run in Github Action using nox.
